import {DurableObject} from "cloudflare:workers";import {DEFAULT_RULES,emptyGame,type Difficulty,type Player,type Rules,type State} from "./model";import {countValue,ends,fullSet,isDouble,legalPlays,ledSuit,setForMoon,shuffle,texas42Contract,trickWinner,type Domino,type Pip,type Trump} from "./rules";
type Env={}; type Client={playerId:string|null};
const AI_PLAY_DELAY_MS=700;
export class GameRoom extends DurableObject<Env>{stateData:State|null=null; sockets=new Map<WebSocket,Client>();
 async executeForTest(c:{type:string;payload?:any;playerId?:string|null;expectedRevision?:number}){const messages:string[]=[];let attachment:Client|undefined;const ws={send:(value:string)=>messages.push(value),serializeAttachment:(value:Client)=>{attachment=value},deserializeAttachment:()=>attachment} as unknown as WebSocket;try{await this.command(ws,c);await this.advanceAI();await this.save();const response=messages.length?JSON.parse(messages.at(-1)!):{};return{ok:true,...response,view:this.view(c.playerId??response.playerId??null)}}catch(error){return{ok:false,error:{message:error instanceof Error?error.message:"Invalid action."},view:this.view(c.playerId??null)}}}
 async viewForTest(playerId:string|null){if(!this.stateData)this.stateData=await this.ctx.storage.get<State>("state")??null;return this.stateData?this.view(playerId):null}
 async initialize(roomId:string){const saved=await this.ctx.storage.get<State>("state");if(saved){this.stateData=saved;return false}this.stateData={roomId,revision:0,hostPlayerId:"",gameType:"moon",players:[],rules:{...DEFAULT_RULES},game:emptyGame(),createdAt:Date.now()};await this.save();return true}
 async fetch(request:Request){const pair=new WebSocketPair();const [client,server]=Object.values(pair);server.serializeAttachment({playerId:null} satisfies Client);this.ctx.acceptWebSocket(server);this.sockets.set(server,{playerId:null});server.send(JSON.stringify({type:"CONNECTED"}));return new Response(null,{status:101,webSocket:client})}
 async webSocketMessage(ws:WebSocket,message:string|ArrayBuffer){try{if(!this.stateData)this.stateData=await this.ctx.storage.get<State>("state")??null;if(!this.stateData)throw new Error("Room not found.");const raw=JSON.parse(String(message)) as {type:string;payload?:any;playerId?:string|null;expectedRevision?:number};await this.command(ws,raw);await this.save();this.broadcast();await this.advanceAIWithBroadcast()}catch(e){ws.send(JSON.stringify({error:{message:e instanceof Error?e.message:"Invalid action."}}))}}
 async webSocketClose(ws:WebSocket){const attached=ws.deserializeAttachment() as Client|undefined;const id=attached?.playerId??this.sockets.get(ws)?.playerId;this.sockets.delete(ws);if(id&&this.stateData){const p=this.stateData.players.find(x=>x.id===id);if(p&&!p.isAI)p.connected=false;await this.save();this.broadcast()}}
 private get s(){if(!this.stateData)throw new Error("Room unavailable.");return this.stateData} private player(id:string|null|undefined){return this.s.players.find(p=>p.id===id)} private actor(ws:WebSocket,raw:any){const attached=ws.deserializeAttachment() as Client|undefined;return this.player(attached?.playerId||this.sockets.get(ws)?.playerId||raw.playerId)}
 private async command(ws:WebSocket,c:{type:string;payload?:any;playerId?:string|null;expectedRevision?:number}){const s=this.s,g=s.game,p=this.actor(ws,c);if(c.type==="CREATE_ROOM"||c.type==="JOIN_ROOM"){if(c.type==="CREATE_ROOM"&&!s.hostPlayerId)s.gameType=c.payload?.gameType==="texas42"?"texas42":"moon";const token=String(c.payload?.reconnectToken||"");let player=token?s.players.find(x=>x.reconnectToken===token):undefined;const seatCount=this.seatCount();if(!player){if(s.players.filter(x=>!x.isAI).length>=seatCount)throw new Error("Room is full.");const seat=Array.from({length:seatCount},(_,i)=>i).find(n=>!s.players.some(x=>x.seat===n));if(seat===undefined)throw new Error("No open chair.");player={id:crypto.randomUUID(),name:String(c.payload?.name||"Player").slice(0,24),seat,score:0,connected:true,ready:false,isAI:false,difficulty:null,reconnectToken:crypto.randomUUID()+crypto.randomUUID(),tricks:0,handPoints:0};s.players.push(player);if(!s.hostPlayerId)s.hostPlayerId=player.id}else{player.connected=true;player.name=String(c.payload?.name||player.name).slice(0,24)}const identity={playerId:player.id};ws.serializeAttachment(identity);this.sockets.set(ws,identity);s.revision++;ws.send(JSON.stringify({playerId:player.id,reconnectToken:player.reconnectToken,view:this.view(player.id)}));return}
 if(!p)throw new Error("Join the room first.");const host=s.hostPlayerId===p.id;if(typeof c.expectedRevision==="number"&&c.expectedRevision>s.revision)throw new Error("Game state changed. Try again.");
 switch(c.type){case"SET_READY":p.ready=Boolean(c.payload?.ready);break;case"ADD_AI":{if(!host||g.phase!=="lobby")throw new Error("Only the host can add AI players.");const seat=Number(c.payload?.seat);if(seat<0||seat>=this.seatCount()||s.players.some(x=>x.seat===seat))throw new Error("That chair is occupied.");const difficulty=(c.payload?.difficulty||"medium") as Difficulty;s.players.push({id:crypto.randomUUID(),name:["Mabel","Arthur","Clara","Jasper"][seat]!,seat,score:0,connected:true,ready:true,isAI:true,difficulty,reconnectToken:null,tricks:0,handPoints:0});break}case"REMOVE_AI":if(!host)throw new Error("Only the host can remove AI players.");s.players=s.players.filter(x=>!(x.isAI&&x.seat===Number(c.payload?.seat)));break;case"UPDATE_RULES":if(!host||g.phase!=="lobby")throw new Error("Rules are locked after play begins.");s.rules={...s.rules,...sanitizeRules(c.payload)};break;case"START_GAME":if(!host||s.players.length!==this.seatCount())throw new Error(`Fill all ${this.seatCount()} chairs first.`);if(s.players.some(x=>!x.ready))throw new Error("Human players must be ready.");this.deal();break;case"BID":this.bid(p,Number(c.payload?.bid));break;case"PASS":this.pass(p);break;case"CHOOSE_TRUMP":this.chooseTrump(p,c.payload?.trump);break;case"DISCARD":this.discard(p,c.payload?.domino);break;case"SKIP_WIDOW":this.skipWidow(p);break;case"PLAY_DOMINO":this.play(p,c.payload?.domino);break;case"NEXT_HAND":if(g.phase!=="hand-end")throw new Error("The hand is not complete.");g.dealerSeat=(g.dealerSeat+1)%this.seatCount();this.deal();break;case"REMATCH":for(const x of s.players){x.score=0;x.tricks=0;x.handPoints=0;x.ready=x.isAI}g.teamMarks=[0,0];g.teamHandPoints=[0,0];g.dealerSeat=(g.dealerSeat+1)%this.seatCount();this.deal();break;default:throw new Error("Unknown action.")}
 s.revision++}
 private deal(){const s=this.s,g=s.game,count=this.seatCount();for(const p of s.players){p.tricks=0;p.handPoints=0}const deck=shuffle(s.gameType==="texas42"?fullSet():setForMoon(s.rules.widow!=="none"));g.hands={};for(let seat=0;seat<count;seat++)g.hands[seat]=[];for(let i=0;i<count*7;i++)g.hands[i%count]!.push(deck[i]!);g.widow=s.gameType==="moon"&&s.rules.widow!=="none"?[deck[21]!]:[];g.discard=null;g.phase="bidding";g.highBid=null;g.bidderSeat=null;g.passed=[];g.trump=null;g.trick=[];g.teamHandPoints=[0,0];g.handNumber++;g.turnSeat=(g.dealerSeat+1)%count;g.message=`${this.at(g.turnSeat).name} opens the bidding.`;g.winnerSeat=null;g.winnerTeam=null}
 private bid(p:Player,bid:number){const s=this.s,g=s.game;if(g.phase!=="bidding"||p.seat!==g.turnSeat)throw new Error("It is not your turn to bid.");if(s.gameType==="texas42"){if(!Number.isInteger(bid)||bid<30||bid>294||bid<=(g.highBid||29)||(bid>42&&bid%42!==0))throw new Error("Texas 42 bids are 30–42 points, then two or more marks.");g.highBid=bid;g.bidderSeat=p.seat;this.nextBidder();return}const max=s.rules.overcallMoon?42:21;if(!Number.isInteger(bid)||bid>max||bid<s.rules.minimumBid||bid<=(g.highBid||0)||![3,4,5,6,7,21,42].includes(bid))throw new Error("That bid is not available.");g.highBid=bid;g.bidderSeat=p.seat;if(bid>=21){this.finishAuction();return}this.nextBidder()}
 private pass(p:Player){const g=this.s.game;if(g.phase!=="bidding"||p.seat!==g.turnSeat)throw new Error("It is not your turn to bid.");g.passed.push(p.seat);this.nextBidder()}
 private nextBidder(){const s=this.s,g=s.game,count=this.seatCount();if(g.passed.length+(g.bidderSeat===null?0:1)>=count||g.passed.length===count){if(g.bidderSeat!==null){this.finishAuction();return}if(s.gameType==="texas42"||s.rules.allPass==="force-dealer"){g.bidderSeat=g.dealerSeat;g.highBid=s.gameType==="texas42"?30:s.rules.minimumBid;this.finishAuction();return}g.dealerSeat=(g.dealerSeat+1)%count;this.deal();g.message="Everyone passed. Dominoes were redealt.";return}let next=(g.turnSeat!+1)%count;while(g.passed.includes(next))next=(next+1)%count;g.turnSeat=next;g.message=`${this.at(next).name} is bidding.`}
 private finishAuction(){const s=this.s,g=s.game;g.turnSeat=g.bidderSeat;if(s.gameType==="texas42"){g.phase="trump";g.message=`${this.at(g.bidderSeat!).name} won the bid and chooses trump.`}else if(s.rules.declareTrumpBeforeWidow){g.phase="trump";g.message=`${this.at(g.bidderSeat!).name} chooses trump before seeing the widow.`}else if(g.widow.length){g.hands[g.bidderSeat!]!.push(g.widow[0]!);g.phase="widow";g.message=`${this.at(g.bidderSeat!).name} picked up the widow.`}else{g.phase="trump";g.message=`${this.at(g.bidderSeat!).name} chooses trump.`}}
 private chooseTrump(p:Player,trump:unknown){const g=this.s.game;if(g.phase!=="trump"||p.seat!==g.bidderSeat)throw new Error("The bidder chooses trump.");if(!(trump==="doubles"||trump==="follow-me"||[0,1,2,3,4,5,6].includes(Number(trump))))throw new Error("Invalid trump.");if(trump==="doubles"&&!this.s.rules.allowDoublesTrump)throw new Error("Doubles trump is disabled.");if(trump==="follow-me"&&!this.s.rules.allowFollowMe)throw new Error("Follow me is disabled.");g.trump=typeof trump==="number"?trump as Pip:trump as Trump;if(this.s.rules.declareTrumpBeforeWidow&&g.widow.length){g.hands[p.seat]!.push(g.widow[0]!);g.phase="widow";g.message=`${p.name} picked up the widow and must discard.`}else this.beginPlay()}
 private discard(p:Player,d:Domino){const g=this.s.game;if(g.phase!=="widow"||p.seat!==g.bidderSeat)throw new Error("Only the bidder discards.");const hand=g.hands[p.seat]!;const i=hand.indexOf(d);if(i<0)throw new Error("That domino is not in your hand.");hand.splice(i,1);g.discard=d;g.widow=[];if(!g.trump){g.phase="trump";g.message=`${p.name} chooses trump.`}else this.beginPlay()}
 private skipWidow(p:Player){const g=this.s.game;if(this.s.rules.widow!=="optional"||g.phase!=="widow"||p.seat!==g.bidderSeat)throw new Error("The widow exchange cannot be skipped.");const hand=g.hands[p.seat]!;const widow=hand.pop();if(widow)g.widow=[widow];if(!g.trump){g.phase="trump";g.message=`${p.name} kept the original hand and chooses trump.`}else this.beginPlay()}
 private beginPlay(){const g=this.s.game;g.phase="playing";g.turnSeat=g.bidderSeat;g.trick=[];g.message=`${this.at(g.turnSeat!).name} leads the first trick.`}
 private play(p:Player,d:Domino){const s=this.s,g=s.game,count=this.seatCount();if(g.phase!=="playing"||p.seat!==g.turnSeat)throw new Error("It is not your turn.");if(g.trick.length===count)g.trick=[];const hand=g.hands[p.seat]!;if(!hand.includes(d))throw new Error("That domino is not in your hand.");const legal=legalPlays(hand,g.trick[0]?.domino??null,g.trump!);if(!legal.includes(d))throw new Error("You must follow the led suit.");hand.splice(hand.indexOf(d),1);g.trick.push({seat:p.seat,domino:d});if(g.trick.length<count){g.turnSeat=(p.seat+1)%count;g.message=`${this.at(g.turnSeat).name} follows.`;return}const winner=trickWinner(g.trick,g.trump!);const winnerPlayer=this.at(winner);winnerPlayer.tricks++;if(s.gameType==="texas42"){const points=1+g.trick.reduce((sum,x)=>sum+countValue(x.domino),0);winnerPlayer.handPoints+=points;g.teamHandPoints[winner%2]+=points}g.turnSeat=winner;g.message=`${winnerPlayer.name} wins the trick.`;if(Object.values(g.hands).every(h=>h.length===0)){this.scoreHand();return}}
 private scoreHand(){const s=this.s,g=s.game,b=this.at(g.bidderSeat!);if(s.gameType==="texas42"){const biddingTeam=b.seat%2,defendingTeam=1-biddingTeam,bid=g.highBid!,points=g.teamHandPoints[biddingTeam],contract=texas42Contract(bid,points);g.teamMarks[contract.made?biddingTeam:defendingTeam]+=contract.marks;for(const p of s.players)p.score=g.teamMarks[p.seat%2];if(g.teamMarks[0]>=7||g.teamMarks[1]>=7){g.phase="complete";g.winnerTeam=g.teamMarks[0]>=7?0:1;g.message=`Team ${g.winnerTeam+1} wins ${g.teamMarks[g.winnerTeam]} marks to ${g.teamMarks[1-g.winnerTeam]}!`}else{g.phase="hand-end";g.message=`${b.name}'s team ${contract.made?"made":"was set on"} ${format42Bid(bid)}. Hand points: ${g.teamHandPoints[0]}–${g.teamHandPoints[1]}.`}return}const made=b.tricks===(g.highBid!>=21?7:g.highBid!)||g.highBid!<21&&b.tricks>=g.highBid!;for(const p of s.players)if(p.seat!==b.seat)p.score+=p.tricks;if(g.highBid!>=21){const stake=g.highBid!;if(s.rules.moonScoring==="instant"){g.phase="complete";g.winnerSeat=made?b.seat:s.players.filter(p=>p.seat!==b.seat).sort((a,c)=>c.score-a.score)[0]!.seat;g.message=made?`${b.name} shot the Moon and wins!`:`${b.name} missed the Moon and loses the game.`;return}b.score+=made?stake:-stake}else b.score+=made?g.highBid!:-g.highBid!;const leaders=[...s.players].filter(p=>p.score>=s.rules.targetScore).sort((a,c)=>c.score-a.score);if(leaders.length){g.phase="complete";g.winnerSeat=leaders[0]!.seat;g.message=`${leaders[0]!.name} wins with ${leaders[0]!.score} points!`}else{g.phase="hand-end";g.message=`${b.name} ${made?"made":"missed"} the bid. ${s.players.map(p=>`${p.name}: ${p.score}`).join(" · ")}`}}
 private async advanceAIWithBroadcast(){for(let guard=0;guard<30;guard++){const g=this.s.game,p=g.turnSeat===null?undefined:this.at(g.turnSeat);if(!p?.isAI)break;const phase=g.phase;if(phase==="playing")await sleep(AI_PLAY_DELAY_MS);if(g.phase==="bidding")this.aiBid(p);else if(g.phase==="trump")this.aiTrump(p);else if(g.phase==="widow")this.aiDiscard(p);else if(g.phase==="playing")this.aiPlay(p);else break;this.s.revision++;await this.save();this.broadcast()}}
 private async advanceAI(){for(let guard=0;guard<30;guard++){const g=this.s.game,p=g.turnSeat===null?undefined:this.at(g.turnSeat);if(!p?.isAI)break;if(g.phase==="bidding")this.aiBid(p);else if(g.phase==="trump")this.aiTrump(p);else if(g.phase==="widow")this.aiDiscard(p);else if(g.phase==="playing")this.aiPlay(p);else break;this.s.revision++}}
 private aiBid(p:Player){const h=this.s.game.hands[p.seat]!;if(this.s.gameType==="texas42"){const strength=h.reduce((n,d)=>n+countValue(d)+(isDouble(d)?3:0),0);const target=Math.min(42,30+Math.floor(strength/7));if(target>(this.s.game.highBid||29))this.bid(p,target);else this.pass(p);return}const strength=h.reduce((n,d)=>n+(isDouble(d)?1.2:0)+(Math.max(...ends(d))/12),0);const target=Math.min(7,Math.max(this.s.rules.minimumBid,Math.floor(strength/1.7)));if(target>(this.s.game.highBid||0))this.bid(p,target);else this.pass(p)}
 private aiTrump(p:Player){const counts=new Map<number,number>();for(const d of this.s.game.hands[p.seat]!)for(const n of new Set(ends(d)))counts.set(n,(counts.get(n)||0)+1);const best=[...counts].sort((a,b)=>b[1]-a[1])[0]?.[0]??6;this.chooseTrump(p,best)}
 private aiDiscard(p:Player){const hand=this.s.game.hands[p.seat]!;const trump=this.s.game.trump;const pick=[...hand].sort((a,b)=>this.aiValue(a,trump)-this.aiValue(b,trump))[0]!;this.discard(p,pick)}
 private aiPlay(p:Player){const g=this.s.game,legal=legalPlays(g.hands[p.seat]!,g.trick[0]?.domino??null,g.trump!);const sorted=[...legal].sort((a,b)=>this.aiValue(a,g.trump)-this.aiValue(b,g.trump));this.play(p,p.difficulty==="easy"?sorted[Math.floor(Math.random()*sorted.length)]!:p.seat===g.bidderSeat?sorted.at(-1)!:sorted[0]!)}
 private aiValue(d:Domino,trump:Trump|null){const[a,b]=ends(d);return Math.max(a,b)+(isDouble(d)?8:0)+(trump!==null&&((typeof trump==="number"&&(a===trump||b===trump))||(trump==="doubles"&&a===b))?12:0)}
 private at(seat:number){const p=this.s.players.find(x=>x.seat===seat);if(!p)throw new Error("Seat unavailable.");return p}
 private seatCount(){return this.s.gameType==="texas42"?4:3} private view(playerId:string|null){const s=this.s,g=s.game,p=this.player(playerId);return{roomId:s.roomId,revision:s.revision,hostPlayerId:s.hostPlayerId,gameType:s.gameType,players:s.players.map(x=>({id:x.id,name:x.name,seat:x.seat,score:x.score,connected:x.connected,ready:x.ready,isAI:x.isAI,difficulty:x.difficulty,dominoCount:g.hands[x.seat]?.length||0,tricks:x.tricks,handPoints:x.handPoints,team:s.gameType==="texas42"?x.seat%2:null})),rules:s.rules,game:{phase:g.phase,dealerSeat:g.dealerSeat,turnSeat:g.turnSeat,bidderSeat:g.bidderSeat,highBid:g.highBid,trump:g.trump,ledSuit:g.trick[0]&&g.trump?ledSuit(g.trick[0].domino,g.trump):null,trick:g.trick,hand:p?[...(g.hands[p.seat]||[])]:[],widowCount:g.widow.length,handNumber:g.handNumber,message:g.message,winnerSeat:g.winnerSeat,teamMarks:g.teamMarks,teamHandPoints:g.teamHandPoints,winnerTeam:g.winnerTeam}}}
 private broadcast(){for(const ws of this.ctx.getWebSockets()){try{const attached=ws.deserializeAttachment() as Client|undefined;ws.send(JSON.stringify({view:this.view(attached?.playerId??null)}))}catch{}}}
 private async save(){if(this.stateData)await this.ctx.storage.put("state",this.stateData)} }
function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
function sanitizeRules(v:any):Partial<Rules>{const out:Partial<Rules>={};if([3,4,5].includes(Number(v?.minimumBid)))out.minimumBid=Number(v.minimumBid) as 3|4|5;if(["redeal","force-dealer"].includes(v?.allPass))out.allPass=v.allPass;if(["exchange","optional","none"].includes(v?.widow))out.widow=v.widow;if(["points","instant"].includes(v?.moonScoring))out.moonScoring=v.moonScoring;for(const k of ["declareTrumpBeforeWidow","allowDoublesTrump","allowFollowMe","overcallMoon"] as const)if(typeof v?.[k]==="boolean")out[k]=v[k];return out}
function format42Bid(bid:number){return bid>42?`${bid/42} marks`:String(bid)}
